language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

before_install:
#  - docker-compose up -d

after_success:
  - mvn clean test jacoco:report coveralls:report

env:
- KAFKA_PORT=29092